name: CI

on:
  push:
    branches: [master]
    tags-ignore: [v*]
  pull_request:
    branches: [master]

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2   # docs: https://github.com/actions/checkout
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*      
    - name: Run build
      run: gradlew.bat build -i --scan --continue

  build:

    runs-on: ubuntu-latest

    needs: windows_build

    steps:
    - uses: actions/checkout@v2   # docs: https://github.com/actions/checkout
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      # when we build tags we may need to fetch the 'master' branch, too
    - name: Run build
      run: ./gradlew build -i --scan --continue
    - name: Deploy to plugins.gradle.org
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: ./gradlew createTag pushTag publishPlugins -i --scan
      env:
          # Gradle env variables docs: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
