name: CI

on:
  push:
    branches: ['**']
    tags-ignore: [v*]
  pull_request:
    branches: ['**']

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2   # docs: https://github.com/actions/checkout
      with:
        # we need a good number of commits to fetch, to generate the release notes
        # we also need tags so that we can deduct the version
        # this project is small, so we will fetch all history ('0')
        # if fetching gets slow we can define a specific # of commits (e.g. '1000')
        fetch-depth: '0'
    - name: Run build
      run: .\gradlew.bat build --scan --continue

  build:

    runs-on: ubuntu-latest

    needs: windows_build

    steps:
    - uses: actions/checkout@v2   # docs: https://github.com/actions/checkout
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      # when we build tags we may need to fetch the 'master' branch, too
    - name: Run build
      run: ./gradlew build --scan --continue
    - name: Push tag and deploy to plugins.gradle.org
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: ./gradlew publishPlugins githubRelease --scan
      env:
          # Gradle env variables docs: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          GH_WRITE_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
