name: CI

on:
  push:
    branches: [master]
    tags-ignore: [v1.*] #TODO needed?
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   # docs: https://github.com/actions/checkout
    - uses: actions/setup-ruby@v1
    - run: gem -h
