name: CI

on:
  push:
    branches: [master]
    tags-ignore: [v1.*] #TODO needed?
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   # docs: https://github.com/actions/checkout
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Run build
      run: ./gradlew build -i --scan --continue
    - name: Deploy to plugins.gradle.org
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: ./gradlew pushTag publishPlugins -i --scan
      env: 
          # Gradle env variables docs: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
