name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   # docs: https://github.com/actions/checkout
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Run build
      run: git tag
#      run: ./gradlew build -i --scan --continue
    - name: Deploy to plugins.gradle.org
      if: success() && github.event_name == 'pushxxx' && github.ref == 'refs/heads/master'
      run: ./gradlew publishPlugins -i --scan
      env: 
          # Gradle env variables docs: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
